name: "⚠️ Bug report"
description: Report errors or unexpected behavior
labels: 
- bug
body:
- type: markdown
  attributes:
    value: |
      Please make sure to [search for existing issues](https://github.com/Aarhus-University-MPE/Ice-Nucleation-Controller/issues) before filing a new one!
- type: input
  attributes:
    label: Ice-Nucleation-Controller version
    placeholder: |
      1.2.12
    description: |
      Check software description
  validations:
    required: true

- type: dropdown
  attributes:
    label: Area(s) with issue?
    description: What things had an issue?  Check all that apply.
    multiple: true
    options:
      - General
      - Ice Nucleation Controller
      - Thermal Camera Evaluation
      - Thermal Camera Calibration
      - Hardware Issue
      - Freezing Point Detection
      - Temperature Controller
      - Performance
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: We highly suggest including screenshots and a bug report log (System tray->Report bug).
    placeholder: Tell us the steps required to trigger your bug.
  validations:
    required: true

- type: textarea
  attributes:
    label: ✔️ Expected Behavior
    placeholder: What were you expecting?
  validations:
    required: false

- type: textarea
  attributes:
    label: ❌ Actual Behavior
    placeholder: What happened instead?
  validations:
    required: false
